const Master = {
  master_access: {
    tablename: 'master_access',
    prefix: 'ma',
    prefix_: 'ma_',
    insertColumns: ['name', 'status'],
    selectColumns: ['ma_id', 'ma_name', 'ma_status'],
    selectOptionColumns: {
      access_id: 'ma_id',
      access_name: 'ma_name',
      status: 'ma_status',
    },
    updateOptionColumns: {
      access_id: 'access_id',
      name: 'name',
      status: 'status',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      access_id: 'INTEGER',
      name: 'STRING',
      status: 'ENUM',
    },
  },
  master_user: {
    tablename: 'master_user',
    prefix: 'mu',
    prefix_: 'mu_',
    insertColumns: ['fullname', 'username', 'password', 'access_id'],
    selectColumns: [
      'mu_id',
      'mu_employee_id',
      'mu_fullname',
      'mu_username',
      'mu_password',
      'mu_access_id',
      'mu_status',
    ],
    selectOptionColumns: {
      id: 'mu_id',
      employee_id: 'mu_employee_id',
      fullname: 'mu_fullname',
      username: 'mu_username',
      password: 'mu_password',
      access_id: 'mu_access_id',
      status: 'mu_status',
    },
    updateOptionColumns: {
      id: 'id',
      employee_id: 'mu_employee_id',
      fullname: 'fullname',
      username: 'username',
      password: 'password',
      access_id: 'access_id',
      status: 'status',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      fullname: 'STRING',
      username: 'STRING',
      password: 'TEXT',
      access_id: 'INTEGER',
      status: 'ENUM',
    },
  },
  master_company: {
    tablename: 'master_company',
    prefix: 'mc',
    prefix_: 'mc_',
    insertColumns: [
      'name',
      'address',
      'email',
      'mobile_number',
      'telephone_number',
      'tin',
      'details',
      'type',
    ],
    selectColumns: [
      'mc_id',
      'mc_name',
      'mc_address',
      'mc_email',
      'mc_mobile_number',
      'mc_telephone_number',
      'mc_tin',
      'mc_details',
      'mc_type',
    ],
    selectOptionColumns: {
      company_id: 'mc_id',
      name: 'mc_name',
      address: 'mc_address',
      email: 'mc_email',
      mobile_number: 'mc_mobile_number',
      telephone_number: 'mc_telephone_number',
      tin: 'mc_tin',
      details: 'mc_details',
      type: 'mc_type',
    },
    updateOptionColumns: {
      company_id: 'company_id',
      name: 'name',
      address: 'address',
      email: 'email',
      mobile_number: 'mobile_number',
      telephone_number: 'telephone_number',
      tin: 'tin',
      details: 'details',
      type: 'type',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      company_id: 'INTEGER',
      name: 'STRING',
      address: 'TEXT',
      email: 'STRING',
      mobile_number: 'STRING',
      telephone_number: 'STRING',
      tin: 'STRING',
      details: 'TEXT',
      type: 'ENUM',
    },
  },
  master_route_access: {
    tablename: 'master_route_access',
    prefix: 'mra',
    prefix_: 'mra_',
    insertColumns: ['access_id', 'name', 'status'],
    selectColumns: ['mra_id', 'mra_access_id', 'mra_name', 'mra_status'],
    selectOptionColumns: {
      id: 'mra_id',
      access_id: 'mra_access_id',
      name: 'mra_name',
      status: 'mra_status',
    },
    updateOptionColumns: {
      id: 'id',
      access_id: 'access_id',
      name: 'name',
      status: 'status',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      access_id: 'INTEGER',
      name: 'STRING',
      status: 'STRING',
    },
  },
  master_department: {
    tablename: 'master_department',
    prefix: 'md',
    prefix_: 'md_',
    insertColumns: ['code', 'description', 'status'],
    selectColumns: ['md_id', 'md_code', 'md_description', 'md_status'],
    selectOptionColumns: {
      id: 'md_id',
      code: 'md_code',
      description: 'md_description',
      status: 'md_status',
    },
    updateOptionColumns: {
      id: 'id',
      code: 'code',
      description: 'description',
      status: 'status',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      code: 'STRING',
      description: 'STRING',
      status: 'ENUM',
    },
  },
  master_service: {
    tablename: 'master_service',
    prefix: 'ms',
    prefix_: 'ms_',
    insertColumns: ['department_id', 'name', 'price', 'status'],
    selectColumns: ['ms_id', 'ms_department_id', 'ms_name', 'ms_price', 'ms_status'],
    selectOptionColumns: {
      id: 'ms_id',
      department_id: 'ms_department_id',
      name: 'ms_name',
      price: 'ms_price',
      status: 'ms_status',
    },
    updateOptionColumns: {
      id: 'id',
      department_id: 'department_id',
      name: 'name',
      price: 'price',
      status: 'status',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      department_id: 'INTEGER',
      name: 'STRING',
      price: 'DECIMAL',
      status: 'ENUM',
    },
  },
  master_store: {
    tablename: 'master_store',
    prefix: 'ms',
    prefix_: 'ms_',
    insertColumns: ['number', 'name', 'region', 'city_province', 'status'],
    selectColumns: ['ms_id', 'ms_number', 'ms_name', 'ms_region', 'ms_city_province', 'ms_status'],
    selectOptionColumns: {
      id: 'ms_id',
      number: 'ms_number',
      name: 'ms_name',
      region: 'ms_region',
      city_province: 'ms_city_province',
      status: 'ms_status',
    },
    updateOptionColumns: {
      id: 'id',
      number: 'number',
      name: 'name',
      region: 'region',
      city_province: 'city_province',
      status: 'status',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      number: 'STRING',
      name: 'STRING',
      region: 'STRING',
      city_province: 'STRING',
      status: 'ENUM',
    },
  },
  charts_of_accounts: {
    tablename: 'charts_of_accounts',
    prefix: 'coa',
    prefix_: 'coa_',
    insertColumns: ['code', 'name', 'type', 'description', 'status'],
    selectColumns: ['coa_id', 'coa_code', 'coa_name', 'coa_type', 'coa_description', 'coa_status'],
    selectOptionColumns: {
      id: 'coa_id',
      code: 'coa_code',
      name: 'coa_name',
      type: 'coa_type',
      description: 'coa_description',
      status: 'coa_status',
    },
    updateOptionColumns: {
      id: 'id',
      code: 'code',
      name: 'name',
      type: 'type',
      description: 'description',
      status: 'status',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      code: 'STRING',
      name: 'STRING',
      type: 'ENUM',
      description: 'TEXT',
      status: 'ENUM',
    },
  },
  customers: {
    tablename: 'customers',
    prefix: 'c',
    prefix_: 'c_',
    insertColumns: ['code', 'name', 'category', 'type', 'status'],
    selectColumns: ['c_id', 'c_code', 'c_name', 'c_category', 'c_type', 'c_status'],
    selectOptionColumns: {
      id: 'c_id',
      code: 'c_code',
      name: 'c_name',
      category: 'c_category',
      type: 'c_type',
      status: 'c_status',
    },
    updateOptionColumns: {
      id: 'id',
      code: 'code',
      name: 'name',
      category: 'category',
      type: 'type',
      status: 'status',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      code: 'STRING',
      name: 'STRING',
      category: 'STRING',
      type: 'STRING',
      status: 'ENUM',
    },
  },
  customers_information: {
    tablename: 'customers_information',
    prefix: 'ci',
    prefix_: 'ci_',
    insertColumns: ['customer_id', 'address', 'tin', 'details', 'contact'],
    selectColumns: ['ci_id', 'ci_customer_id', 'ci_address', 'ci_tin', 'ci_details', 'ci_contact'],
    selectOptionColumns: {
      id: 'ci_id',
      customer_id: 'ci_customer_id',
      address: 'ci_address',
      tin: 'ci_tin',
      details: 'ci_details',
      contact: 'ci_contact',
    },
    updateOptionColumns: {
      id: 'id',
      customer_id: 'customer_id',
      address: 'address',
      tin: 'tin',
      details: 'details',
      contact: 'contact',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      customer_id: 'INTEGER',
      address: 'TEXT',
      tin: 'STRING',
      details: 'TEXT',
      contact: 'STRING',
    },
  },
  proforma_entries: {
    tablename: 'proforma_entries',
    prefix: 'pe',
    prefix_: 'pe_',
    insertColumns: ['module', 'name', 'coa_id', 't_account'],
    selectColumns: ['pe_id', 'pe_module', 'pe_name', 'pe_coa_id', 'pe_t_account'],
    selectOptionColumns: {
      id: 'pe_id',
      module: 'pe_module',
      name: 'pe_name',
      coa_id: 'pe_coa_id',
      t_account: 'pe_t_account',
    },
    updateOptionColumns: {
      id: 'id',
      module: 'module',
      name: 'name',
      coa_id: 'coa_id',
      t_account: 't_account',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      module: 'STRING',
      name: 'STRING',
      coa_id: 'INTEGER',
      t_account: 'STRING',
    },
  },
  vendors: {
    tablename: 'vendors',
    prefix: 'v',
    prefix_: 'v_',
    insertColumns: ['code', 'name', 'category', 'type', 'status'],
    selectColumns: ['v_id', 'v_code', 'v_name', 'v_category', 'v_type', 'v_status'],
    selectOptionColumns: {
      id: 'v_id',
      code: 'v_code',
      name: 'v_name',
      category: 'v_category',
      type: 'v_type',
      status: 'v_status',
    },
    updateOptionColumns: {
      id: 'id',
      code: 'code',
      name: 'name',
      category: 'category',
      type: 'type',
      status: 'status',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      code: 'STRING',
      name: 'STRING',
      category: 'STRING',
      type: 'STRING',
      status: 'ENUM',
    },
  },
  vendors_information: {
    tablename: 'vendors_information',
    prefix: 'vi',
    prefix_: 'vi_',
    insertColumns: ['vendor_id', 'address', 'tin', 'details', 'contact'],
    selectColumns: ['vi_id', 'vi_vendor_id', 'vi_address', 'vi_tin', 'vi_details', 'vi_contact'],
    selectOptionColumns: {
      id: 'vi_id',
      vendor_id: 'vi_vendor_id',
      address: 'vi_address',
      tin: 'vi_tin',
      details: 'vi_details',
      contact: 'vi_contact',
    },
    updateOptionColumns: {
      id: 'id',
      vendor_id: 'vendor_id',
      address: 'address',
      tin: 'tin',
      details: 'details',
      contact: 'contact',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      vendor_id: 'INTEGER',
      address: 'TEXT',
      tin: 'STRING',
      details: 'TEXT',
      contact: 'STRING',
    },
  },
  products_service: {
    tablename: 'products_service',
    prefix: 'ps',
    prefix_: 'ps_',
    insertColumns: ['code', 'name', 'type', 'category', 'sales_price', 'purchase_price', 'unit'],
    selectColumns: [
      'ps_id',
      'ps_code',
      'ps_name',
      'ps_type',
      'ps_category',
      'ps_sales_price',
      'ps_purchase_price',
      'ps_unit',
    ],
    selectOptionColumns: {
      id: 'ps_id',
      code: 'ps_code',
      name: 'ps_name',
      type: 'ps_type',
      category: 'ps_category',
      sales_price: 'ps_sales_price',
      purchase_price: 'ps_purchase_price',
      unit: 'ps_unit',
    },
    updateOptionColumns: {
      id: 'id',
      code: 'code',
      name: 'name',
      type: 'type',
      category: 'category',
      sales_price: 'sales_price',
      purchase_price: 'purchase_price',
      unit: 'unit',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      code: 'STRING',
      name: 'STRING',
      type: 'ENUM',
      category: 'STRING',
      sales_price: 'INTEGER',
      purchase_price: 'INTEGER',
      unit: 'STRING',
    },
  },
  vat: {
    tablename: 'vat',
    prefix: 'vat',
    prefix_: 'vat_',
    insertColumns: ['code', 'name', 'rate', 'type', 'sub_type', 'description', 'status'],
    selectColumns: [
      'vat_id',
      'vat_code',
      'vat_name',
      'vat_rate',
      'vat_type',
      'vat_sub_type',
      'vat_description',
      'vat_status',
    ],
    selectOptionColumns: {
      id: 'vat_id',
      code: 'vat_code',
      name: 'vat_name',
      rate: 'vat_rate',
      type: 'vat_type',
      sub_type: 'vat_sub_type',
      description: 'vat_description',
      status: 'vat_status',
    },
    updateOptionColumns: {
      id: 'id',
      code: 'code',
      name: 'name',
      rate: 'rate',
      type: 'type',
      sub_type: 'sub_type',
      description: 'description',
      status: 'status',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      code: 'STRING',
      name: 'STRING',
      rate: 'DECIMAL',
      type: 'ENUM',
      sub_type: 'ENUM',
      description: 'TEXT',
      status: 'ENUM',
    },
  },
  withholding_tax: {
    tablename: 'withholding_tax',
    prefix: 'wt',
    prefix_: 'wt_',
    insertColumns: ['code', 'name', 'rate', 'tax_account', 'description', 'status'],
    selectColumns: [
      'wt_id',
      'wt_code',
      'wt_name',
      'wt_rate',
      'wt_tax_account',
      'wt_description',
      'wt_status',
    ],
    selectOptionColumns: {
      id: 'wt_id',
      code: 'wt_code',
      name: 'wt_name',
      rate: 'wt_rate',
      tax_account: 'wt_tax_account',
      description: 'wt_description',
      status: 'wt_status',
    },
    updateOptionColumns: {
      id: 'id',
      code: 'code',
      name: 'name',
      rate: 'rate',
      tax_account: 'tax_account',
      description: 'description',
      status: 'status',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      code: 'STRING',
      name: 'STRING',
      rate: 'DECIMAL',
      tax_account: 'STRING',
      description: 'TEXT',
      status: 'ENUM',
    },
  },
  audit_trail: {
    tablename: 'audit_trail',
    prefix: 'at',
    prefix_: 'at_',
    insertColumns: [
      'transaction_id',
      'module',
      'performed_by',
      'created_date',
      'created_time',
      'action',
    ],
    selectColumns: [
      'at_id',
      'at_transaction_id',
      'at_module',
      'at_performed_by',
      'at_created_date',
      'at_created_time',
      'at_action',
    ],
    selectOptionColumns: {
      id: 'at_id',
      transaction_id: 'at_transaction_id',
      module: 'at_module',
      performed_by: 'at_performed_by',
      created_date: 'at_created_date',
      created_time: 'at_created_time',
      action: 'at_action',
    },
    updateOptionColumns: {
      id: 'id',
      transaction_id: 'transaction_id',
      module: 'module',
      performed_by: 'performed_by',
      created_date: 'created_date',
      created_time: 'created_time',
      action: 'action',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      transaction_id: 'STRING',
      module: 'STRING',
      performed_by: 'STRING',
      created_date: 'STRING',
      created_time: 'STRING',
      action: 'STRING',
    },
  },
  master_parts: {
    tablename: 'master_parts',
    prefix: 'mp',
    prefix_: 'mp_',
    insertColumns: ['name', 'description', 'price', 'status'],
    selectColumns: ['mp_id', 'mp_name', 'mp_description', 'mp_price', 'mp_status'],
    selectOptionColumns: {
      id: 'mp_id',
      name: 'mp_name',
      description: 'mp_description',
      price: 'mp_price',
      status: 'mp_status',
    },
    updateOptionColumns: {
      id: 'id',
      name: 'name',
      description: 'description',
      price: 'price',
      status: 'status',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      name: 'STRING',
      description: 'TEXT',
      price: 'DECIMAL',
      status: 'ENUM',
    },
  },
}

exports.Master = Master
