const Statement = {
  statement_of_account: {
    tablename: 'statement_of_account',
    prefix: 'soa',
    prefix_: 'soa_',
    insertColumns: [
      'company_from',
      'company_to',
      'date',
      'title',
      'headers',
      'sub_total',
      'vat',
      'total',
      'prepared_by',
      'statement_type',
      'maintenance_format',
    ],
    selectColumns: [
      'soa_id',
      'soa_company_from',
      'soa_company_to',
      'soa_date',
      'soa_title',
      'soa_headers',
      'soa_sub_total',
      'soa_vat',
      'soa_total',
      'soa_prepared_by',
      'soa_statement_type',
      'soa_maintenance_format',
    ],
    selectOptionColumns: {
      id: 'soa_id',
      company_from: 'soa_company_from',
      company_to: 'soa_company_to',
      date: 'soa_date',
      title: 'soa_title',
      headers: 'soa_headers',
      sub_total: 'soa_sub_total',
      vat: 'soa_vat',
      total: 'soa_total',
      prepared_by: 'soa_prepared_by',
      statement_type: 'soa_statement_type',
      maintenance_format: 'soa_maintenance_format',
    },
    updateOptionColumns: {
      id: 'id',
      company_from: 'company_from',
      company_to: 'company_to',
      date: 'date',
      title: 'title',
      headers: 'headers',
      sub_total: 'sub_total',
      vat: 'vat',
      total: 'total',
      prepared_by: 'prepared_by',
      statement_type: 'statement_type',
      maintenance_format: 'maintenance_format',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      company_from: 'INTEGER',
      company_to: 'INTEGER',
      date: 'STRING',
      title: 'STRING',
      headers: 'JSON',
      sub_total: 'DECIMAL',
      vat: 'DECIMAL',
      total: 'DECIMAL',
      prepared_by: 'STRING',
      statement_type: 'ENUM',
      maintenance_format: 'ENUM',
    },
  },
  statement_items: {
    tablename: 'statement_items',
    prefix: 'si',
    prefix_: 'si_',
    insertColumns: ['statement_id', 'items'],
    selectColumns: ['si_id', 'si_statement_id', 'si_items'],
    selectOptionColumns: {
      id: 'si_id',
      statement_id: 'si_statement_id',
      items: 'si_items',
    },
    updateOptionColumns: {
      id: 'id',
      statement_id: 'statement_id',
      items: 'items',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      statement_id: 'INTEGER',
      items: 'JSON',
    },
  },
  statement_activity: {
    tablename: 'statement_activity',
    prefix: 'sa',
    prefix_: 'sa_',
    insertColumns: ['statement_id', 'action', 'by', 'date'],
    selectColumns: ['sa_id', 'sa_statement_id', 'sa_action', 'sa_by', 'sa_date'],
    selectOptionColumns: {
      id: 'sa_id',
      statement_id: 'sa_statement_id',
      action: 'sa_action',
      by: 'sa_by',
      date: 'sa_date',
    },
    updateOptionColumns: {
      id: 'id',
      statement_id: 'statement_id',
      action: 'action',
      by: 'by',
      date: 'date',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      statement_id: 'INTEGER',
      action: 'TEXT',
      by: 'STRING',
      date: 'STRING',
    },
  },
}

exports.Statement = Statement
